<?php

ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

session_start();
require 'vendor/autoload.php';

use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;
require 'vendor/tecnickcom/tcpdf/tcpdf.php';

$pdf = new \TCPDF();

// Database connection
$conn = new mysqli('localhost', 'polyflash', 'VdrElE3A13FS3.1F', 'polyflash');

if ($conn->connect_error) {
    die("Connection failed: " . $conn->connect_error);
}

$response = array('success' => false);

if ($_SERVER['REQUEST_METHOD'] == 'POST' && isset($_POST['otp'])) {

    $otp = $_POST['otp'];
    $email = 'mrk.nmc@psgtech.ac.in';  

    $stmt = $conn->prepare("SELECT * FROM otpVerification WHERE email = ? AND otp = ?");
    $stmt->bind_param("ss", $email, $otp);
    $stmt->execute();
    $result = $stmt->get_result();

    if ($result->num_rows > 0) {
        $_SESSION['otp_verified'] = true;
        $response['success'] = true;

        // Set document information
        $pdf->SetCreator(PDF_CREATOR);
        $pdf->SetAuthor('Your Name');
        $pdf->SetTitle('CUG SIM KYC DOCUMENT');
        $pdf->SetSubject('TCPDF Tutorial');
        $pdf->SetKeywords('TCPDF, PDF, example, test, guide');

        // Set default header data
        $pdf->SetHeaderData('', 0, 'CUG SIM KYC DOCUMENT', 'Generated by TCPDF');

        // Set header and footer fonts
        $pdf->setHeaderFont(Array('helvetica', '', 10));
        $pdf->setFooterFont(Array('helvetica', '', 8));

        // Set margins
        $pdf->SetMargins(10, 10, 10);
        $pdf->SetHeaderMargin(10);
        $pdf->SetFooterMargin(10);

        // Add a page
        $pdf->AddPage();
        $pdf->SetFont('helvetica', '', 12);

        // Load HTML content
        $html = file_get_contents('test.html');

        if ($html === false) {
            $response['message'] = 'Error loading HTML content.';
            echo json_encode($response);
            exit;
        }

        // Write HTML to PDF
        try {
            $pdf->writeHTML($html, true, false, true, false, '');
        } catch (Exception $e) {
            $response['message'] = "Error writing HTML to PDF: " . $e->getMessage();
            echo json_encode($response);
            exit;
        }

        // Define the path for the PDF file
        $pdfFilePath = 'tmp/otp_' . time() . '.pdf';

        // Ensure the directory exists
        if (!is_dir('tmp')) {
            if (!mkdir('tmp', 0755, true)) {
                $response['message'] = 'Failed to create temporary directory.';
                echo json_encode($response);
                exit;
            }
        }

        // Output PDF to the file system
        try {
            $pdf->Output($pdfFilePath, 'F');
            $response['pdfUrl'] = $pdfFilePath;
        } catch (Exception $e) {
            $response['message'] = "PDF generation error: " . $e->getMessage();
            echo json_encode($response);
            exit;
        }

        // Prepare email
        $mail = new PHPMailer(true);

        try {
            $mail->isSMTP();
            $mail->Host       = 'smtp.gmail.com';
            $mail->SMTPAuth   = true;
            $mail->Username   = 'no-reply.nmc@psgtech.ac.in'; 
            $mail->Password   = '@mrmg-nmc@2023'; 
            $mail->SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS;
            $mail->Port       = 587;

            $mail->setFrom('no-reply.nmc@psgtech.ac.in', 'OTP');
            $mail->addAddress('mrk.nmc@psgtech.ac.in');

            $mail->isHTML(true);
            $mail->Subject = 'PDF';
            $mail->Body    = "Please find your OTP code attached in the PDF document.";

            $mail->addAttachment($pdfFilePath);

            $mail->send();
            $response['message'] = 'OTP and PDF have been sent to your email!';
        } catch (Exception $e) {
            $response['message'] = "Mailer Error: {$mail->ErrorInfo}";
        }

        // Clean up the temporary file
        if (file_exists($pdfFilePath)) {
            unlink($pdfFilePath);
        }

        $stmt->close();
    } else {
        $response['message'] = 'Invalid OTP or email address.';
    }
}

$conn->close();

ob_get_clean(); // Clear any buffered output
header('Content-Type: application/json');
echo json_encode($response);


// ini_set('display_errors', 1);
// ini_set('display_startup_errors', 1);
// error_reporting(E_ALL);

// session_start();
// require 'vendor/autoload.php';
// require('vendor/setasign/fpdf/fpdf.php');

// use PHPMailer\PHPMailer\PHPMailer;
// use PHPMailer\PHPMailer\Exception;

// require 'vendor/tecnickcom/tcpdf/tcpdf.php';
// $pdf = new \TCPDF();
// // Database connection
// $conn = new mysqli('localhost', 'polyflash', 'VdrElE3A13FS3.1F', 'polyflash');

// if ($conn->connect_error) {
//     die("Connection failed: " . $conn->connect_error);
// }

// $response = array('success' => false);

// if ($_SERVER['REQUEST_METHOD'] == 'POST' && isset($_POST['otp'])) {

//     $otp = $_POST['otp'];
//     $email = 'mrk.nmc@psgtech.ac.in';  

//     $stmt = $conn->prepare("SELECT * FROM otpVerification WHERE email = ? AND otp = ?");
//     $stmt->bind_param("ss", $email, $otp);
//     $stmt->execute();
//     $result = $stmt->get_result();

//     if ($result->num_rows > 0) {
//         $_SESSION['otp_verified'] = true;
//         $response['success'] = true;
        
//          // Set document information
//          $pdf->SetCreator(PDF_CREATOR);
//          $pdf->SetAuthor('Your Name');
//          $pdf->SetTitle('CUG SIM KYC DOCUMENT');
//          $pdf->SetSubject('TCPDF Tutorial');
//          $pdf->SetKeywords('TCPDF, PDF, example, test, guide');
//           // Set default header data
//         $pdf->SetHeaderData('', 0, 'CUG SIM KYC DOCUMENT', 'Generated by TCPDF');

//         // Set header and footer fonts
//         $pdf->setHeaderFont(Array('helvetica', '', 10));
//         $pdf->setFooterFont(Array('helvetica', '', 8));

//         // Set margins
//         $pdf->SetMargins(10, 10, 10);
//         $pdf->SetHeaderMargin(10);
//         $pdf->SetFooterMargin(10);

//         // Add a page
//         $pdf->AddPage();
//         $pdf->SetFont('helvetica', '', 12);
//         $html = file_get_contents('test.html');

//         $pdf->writeHTML($html, true, false, true, false, '');
//         // $pdfFilePath = 'output.pdf';
//         // $pdf->Output($pdfFilePath, 'F');       
         
//         $pdfFilePath = 'otp_' . time() . '.pdf';
//         // $pdf->Output('F', $pdfFilePath);
//         try {
//             $pdf->Output($pdfFilePath, 'F');
//             $response['pdfUrl'] = $pdfFilePath;
//         } catch (Exception $e) {
//             $response['message'] = "PDF generation error: " . $e->getMessage();
//             echo json_encode($response);
//             exit;
//         }
        
//         $response['pdfUrl'] = $pdfFilePath;
//     }

//     $mail = new PHPMailer(true);

//     try {
//         $mail->isSMTP();
//         $mail->Host       = 'smtp.gmail.com';
//         $mail->SMTPAuth   = true;
//         $mail->Username   = 'no-reply.nmc@psgtech.ac.in'; 
//         $mail->Password   = '@mrmg-nmc@2023'; 
//         $mail->SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS;
//         $mail->Port       = 587;

//         $mail->setFrom('no-reply.nmc@psgtech.ac.in', 'OTP');
//         $mail->addAddress('mrk.nmc@psgtech.ac.in');

//         $mail->isHTML(true);
//         $mail->Subject = 'PDF';
//         $mail->Body    = "please find your OTP code attached in the PDF document.";

//         $mail->addAttachment($pdfFilePath);

//         $mail->send();
//         $response['message'] = 'OTP and PDF have been sent to your email!';
//     } catch (Exception $e) {
//         $response['message'] = "Message could not be sent. Mailer Error: {$mail->ErrorInfo}";
//     }

//     $stmt->close();


// }

// $conn->close();

// ob_clean(); // Clear any buffered output
// header('Content-Type: application/json');
// echo json_encode($response);

// ini_set('display_errors', 1);
// ini_set('display_startup_errors', 1);
// error_reporting(E_ALL);

// session_start();
// require 'vendor/autoload.php';
// require('vendor/setasign/fpdf/fpdf.php');

// use PHPMailer\PHPMailer\PHPMailer;
// use PHPMailer\PHPMailer\Exception;

// // Database connection
// $conn = new mysqli('localhost', 'polyflash', 'VdrElE3A13FS3.1F', 'polyflash');

// if ($conn->connect_error) {
//     die("Connection failed: " . $conn->connect_error);
// }

// $response = array('success' => false);

// if ($_SERVER['REQUEST_METHOD'] == 'POST' && isset($_POST['otp'])) {

//     $otp = $_POST['otp'];
//     $email = 'mrk.nmc@psgtech.ac.in';  

//     $stmt = $conn->prepare("SELECT * FROM otpVerification WHERE email = ? AND otp = ?");
//     // $stmt = $conn->prepare("SELECT * FROM otpVerification WHERE email = ? AND otp = ? AND TIMESTAMPDIFF(MINUTE, created_at, NOW()) <= 10");
//     $stmt->bind_param("ss", $email, $otp);
//     $stmt->execute();
//     $result = $stmt->get_result();

//     if ($result->num_rows > 0) {
       
//         $response['success'] = true;
//         class PDF extends FPDF
//         {
//             function Header()
//             {
//                 $this->SetFont('Arial', 'B', 16);
//                 $this->Cell(0, 10, 'PSG Institutions, Coimbatore', 0, 1, 'C');
//                 $this->Cell(0, 10, 'CUG SIM KYC DOCUMENT', 0, 1, 'C');
//                 $this->Ln(10);
//             }

//             function Footer()
//             {
//                 $this->SetY(-15);
//                 $this->SetFont('Arial', 'I', 8);
//                 $this->Cell(0, 10, 'Page ' . $this->PageNo(), 0, 0, 'C');
//             }
//         }

//         // Create instance of FPDF
//         $pdf = new PDF();
//         $pdf->AddPage();
//         $pdf->SetFont('Arial', '', 12);

//         // Document content
//         $content = [
//             'CUG Mobile No' => '______________________',
//             '20 Digit SIM No' => '______________________',
//             'Institution name' => '______________________',
//             'Employee No' => '______________________',
//             'Name of the user' => '______________________',
//             'Personal Mobile No' => '______________________',
//             'Official Email ID' => '______________________',
//             'User Aadhar No' => '______________________',
//             'Issued with handset' => 'Yes / No',
//             'SIM type' => 'Physical SIM / eSIM',
//             'SIM Received Date' => '______________________',
//             'SIM Issued by' => '______________________',
//             'SIM Used in' => 'Slot 1 / Slot 2',
//             'Using Mobile data' => 'Yes / No',
//             'Device type' => 'Smartphone / Button type / Tablet / iPad / Data card / Others',
//             'Average calls per day' => '______________________',
//             'Purpose' => '______________________',
//             'Is this number registered in any websites?' => 'Yes / No',
//             'Used in WhatsApp' => 'Yes / No',
//             'SIM location' => '______________________',
//         ];

//         foreach ($content as $key => $value) {
//             $pdf->Cell(0, 10, $key . ': ' . $value, 0, 1);
//         }

//         // Instructions
//         $instructions = [
//             'CUG numbers should not be used for any kind of personal calls / personal purposes.',
//             'KYC must be validated once in six months, through online mode (https://cug.psginstitutions.in)',
//             'SIM should be surrendered during cessation of the service.',
//             'SIM user must be available 24/7 to attend the calls.'
//         ];

//         $pdf->Ln(10);
//         $pdf->SetFont('Arial', 'B', 12);
//         $pdf->Cell(0, 10, 'Instructions', 0, 1);

//         $pdf->SetFont('Arial', '', 12);
//         foreach ($instructions as $instruction) {
//             $pdf->MultiCell(0, 10, $instruction);
//         }

//         // $pdf = new FPDF();
//         // $pdf->AddPage();
//         // $pdf->SetFont('Arial', 'B', 16);
//         // $pdf->Cell(40, 10, "Your OTP Code:");
//         // $pdf->Ln();
//         // $pdf->Cell(40, 10, $otp);
//         // $pdf->Ln();
//         // $pdf->Cell(40, 10, "Email: $email");
//         $pdfFilePath = 'otp_' . time() . '.pdf';
//         $pdf->Output('F', $pdfFilePath);

//         $response['pdfUrl'] = $pdfFilePath;
//     }

//     $mail = new PHPMailer(true);

//     try {
//         $mail->isSMTP();
//         $mail->Host       = 'smtp.gmail.com';
//         $mail->SMTPAuth   = true;
//         $mail->Username   = 'no-reply.nmc@psgtech.ac.in'; 
//         $mail->Password   = '@mrmg-nmc@2023'; 
//         $mail->SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS;
//         $mail->Port       = 587;

//         $mail->setFrom('no-reply.nmc@psgtech.ac.in', 'OTP');
//         $mail->addAddress('mrk.nmc@psgtech.ac.in');

//         $mail->isHTML(true);
//         $mail->Subject = 'Your OTP Code with PDF';
//         $mail->Body    = "Dear  please find your OTP code attached in the PDF document.";

//         // Attach the PDF
//         $mail->addAttachment($pdfFilePath);

//         $mail->send();
//         echo 'OTP and PDF have been sent to your email!';
//     } catch (Exception $e) {
//         echo "Message could not be sent. Mailer Error: {$mail->ErrorInfo}";
//     }


//     $stmt->close();
// }

// $conn->close();

// ob_clean(); 
// header('Content-Type: application/json');
// echo json_encode($response);



// // working 

// ini_set('display_errors', 1);
// ini_set('display_startup_errors', 1);
// error_reporting(E_ALL);

// session_start();
// require 'vendor/autoload.php';
// require('vendor/setasign/fpdf/fpdf.php');

// use PHPMailer\PHPMailer\PHPMailer;
// use PHPMailer\PHPMailer\Exception;

// // Database connection
// $conn = new mysqli('localhost', 'polyflash', 'VdrElE3A13FS3.1F', 'polyflash');

// if ($conn->connect_error) {
//     die("Connection failed: " . $conn->connect_error);
// }

// $response = array('success' => false);

// if ($_SERVER['REQUEST_METHOD'] == 'POST' && isset($_POST['otp'])) {

//     $otp = $_POST['otp'];
//     $email = 'mrk.nmc@psgtech.ac.in';  

//     $stmt = $conn->prepare("SELECT * FROM otpVerification WHERE email = ? AND otp = ?");
//     // $stmt = $conn->prepare("SELECT * FROM otpVerification WHERE email = ? AND otp = ? AND TIMESTAMPDIFF(MINUTE, created_at, NOW()) <= 10");
//     $stmt->bind_param("ss", $email, $otp);
//     $stmt->execute();
//     $result = $stmt->get_result();

//     if ($result->num_rows > 0) {
       
//         $response['success'] = true;
//         class PDF extends FPDF
//         {
//             function Header()
//             {
//                 $this->SetFont('Arial', 'B', 16);
//                 $this->Cell(0, 10, 'PSG Institutions, Coimbatore', 0, 1, 'C');
//                 $this->Cell(0, 10, 'CUG SIM KYC DOCUMENT', 0, 1, 'C');
//                 $this->Ln(10);
//             }

//             function Footer()
//             {
//                 $this->SetY(-15);
//                 $this->SetFont('Arial', 'I', 8);
//                 $this->Cell(0, 10, 'Page ' . $this->PageNo(), 0, 0, 'C');
//             }
//         }

//         // Create instance of FPDF
//         $pdf = new PDF();
//         $pdf->AddPage();
//         $pdf->SetFont('Arial', '', 12);

//         // Document content
//         $content = [
//             'CUG Mobile No' => '______________________',
//             '20 Digit SIM No' => '______________________',
//             'Institution name' => '______________________',
//             'Employee No' => '______________________',
//             'Name of the user' => '______________________',
//             'Personal Mobile No' => '______________________',
//             'Official Email ID' => '______________________',
//             'User Aadhar No' => '______________________',
//             'Issued with handset' => 'Yes / No',
//             'SIM type' => 'Physical SIM / eSIM',
//             'SIM Received Date' => '______________________',
//             'SIM Issued by' => '______________________',
//             'SIM Used in' => 'Slot 1 / Slot 2',
//             'Using Mobile data' => 'Yes / No',
//             'Device type' => 'Smartphone / Button type / Tablet / iPad / Data card / Others',
//             'Average calls per day' => '______________________',
//             'Purpose' => '______________________',
//             'Is this number registered in any websites?' => 'Yes / No',
//             'Used in WhatsApp' => 'Yes / No',
//             'SIM location' => '______________________',
//         ];

//         foreach ($content as $key => $value) {
//             $pdf->Cell(0, 10, $key . ': ' . $value, 0, 1);
//         }

//         // Instructions
//         $instructions = [
//             'CUG numbers should not be used for any kind of personal calls / personal purposes.',
//             'KYC must be validated once in six months, through online mode (https://cug.psginstitutions.in)',
//             'SIM should be surrendered during cessation of the service.',
//             'SIM user must be available 24/7 to attend the calls.'
//         ];

//         $pdf->Ln(10);
//         $pdf->SetFont('Arial', 'B', 12);
//         $pdf->Cell(0, 10, 'Instructions', 0, 1);

//         $pdf->SetFont('Arial', '', 12);
//         foreach ($instructions as $instruction) {
//             $pdf->MultiCell(0, 10, $instruction);
//         }

//         // $pdf = new FPDF();
//         // $pdf->AddPage();
//         // $pdf->SetFont('Arial', 'B', 16);
//         // $pdf->Cell(40, 10, "Your OTP Code:");
//         // $pdf->Ln();
//         // $pdf->Cell(40, 10, $otp);
//         // $pdf->Ln();
//         // $pdf->Cell(40, 10, "Email: $email");
//         $pdfFilePath = 'otp_' . time() . '.pdf';
//         $pdf->Output('F', $pdfFilePath);

//         $response['pdfUrl'] = $pdfFilePath;
//     }

//     $mail = new PHPMailer(true);

//     try {
//         $mail->isSMTP();
//         $mail->Host       = 'smtp.gmail.com';
//         $mail->SMTPAuth   = true;
//         $mail->Username   = 'no-reply.nmc@psgtech.ac.in'; 
//         $mail->Password   = '@mrmg-nmc@2023'; 
//         $mail->SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS;
//         $mail->Port       = 587;

//         $mail->setFrom('no-reply.nmc@psgtech.ac.in', 'OTP');
//         $mail->addAddress('mrk.nmc@psgtech.ac.in');

//         $mail->isHTML(true);
//         $mail->Subject = 'Your OTP Code with PDF';
//         $mail->Body    = "Dear  please find your OTP code attached in the PDF document.";

//         // Attach the PDF
//         $mail->addAttachment($pdfFilePath);

//         $mail->send();
//         echo 'OTP and PDF have been sent to your email!';
//     } catch (Exception $e) {
//         echo "Message could not be sent. Mailer Error: {$mail->ErrorInfo}";
//     }


//     $stmt->close();
// }

// $conn->close();

// header('Content-Type: application/json');
// echo json_encode($response);

